### ISSUE TITLE
OpenAIの出力結果調整

### ISSUE THREAD

**Issue by keit0728** [XYLOCOPA3/prompt-dungeons#15]
出力フォーマットをどう返すべきかを考える

**Comment by kmt0719** [comment]
- jsonで返す？
- dog/cat の例のようにしっかりと出力形式を例示してchatGPTに指定する？
- 1階層毎にアンサーをもらう？
- 1階層毎に出力する
- ダンジョンの階層名と階層主はアンサーでもらう必要なし。こっちで慈善定義する

**Comment by keit0728** [comment]
- 1: キャラクター名を入力
- 1: キャラクターのフレーバーテキスト20文字生成
- 1: 3択でスキル選択（キャラクター名から自動生成）
- 2: 1階層目の探索の様子を自動生成
- 2: 1階層目のボスを表示（名前、画像）
- 2: 戦闘テキスト生成（ドラクエ風）
- 2: 勝ったら次へ、負けたら終わり
- 3: 2の流れを10階層まで繰り返す
- 4: クリアしたらDB保存（将来的にインセンティブ渡す）
